FROM node:23-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app/apps/2048-express


COPY ./apps/2048-express  /app/apps/2048-express
COPY ./packages/shared-2048-logic /app/packages/shared-2048-logic

RUN pnpm install 


ENV CHOKIDAR_USEPOLLING=true

EXPOSE 8000

CMD ["pnpm", "dev"]
