services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/2048-next/Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    command: ["pnpm", "start"]

  backend:
    build:
      context: .
      dockerfile: ./apps/2048-express/Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "8000:8000"
    command: ["pnpm", "start"]
