FROM node:23-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app/apps/2048-next

COPY ./apps/2048-next  /app/apps/2048-next
COPY ./packages/shared-2048-logic /app/packages/shared-2048-logic

RUN pnpm install

EXPOSE 3000

ENV CHOKIDAR_USEPOLLING=true

CMD ["pnpm", "dev"]
